# Generated by Django 5.0.6 on 2024-06-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
