# Generated by Django 5.1 on 2024-08-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_favorito_fav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
